name: Dev branch checks

on:
  pull_request:
    branches: 
    - dev

jobs:
  build:
    name: Basicv flutter test
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter pub test
